version: '3.8'
services:
  minio1:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9091:9091"
    command: "server /data --console-address ':9091'"
    environment:
      MINIO_ACCESS_KEY: "FAKE_ACCESS_KEY"
      MINIO_SECRET_KEY: "FAKE_SECRET_ACCESS_KEY"
